/*
 Author Phang Chun Wai
 */
package ui;

import da.StaffDA;
import domain.Icon;
import java.io.File;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import control.MaintainStaffControl;
import domain.Staff;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Phw
 */
public class MaintainStaff extends javax.swing.JFrame {

    private final MaintainStaffControl stfControl;
    private final String filename = "";
    private ImageIcon imgPhoto;
    private final JFileChooser jfcPhoto = new JFileChooser();
    private String stf ;
    /**
     * Creates new form Maintain
     * @throws java.lang.Exception
     */
    public MaintainStaff(Staff staff) throws Exception {
        stfControl = new MaintainStaffControl();
        stf = staff.getId();
        initComponents();
        
        
        jlClick.setVisible(false);
        jlPassword.setVisible(false);
        jlAdd.setVisible(false);
        setTitle("Staffing Menu");
         setSize(690, 650);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        
    }
    
    
    public MaintainStaff()  {
        stfControl = new MaintainStaffControl();
       
        initComponents();
        
        
        jlClick.setVisible(false);
        jlPassword.setVisible(false);
        jlAdd.setVisible(false);
        setTitle("Staffing Menu");
         setSize(690, 650);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private class WindowCloseListener extends WindowAdapter {

        @Override
        public void windowClosed(WindowEvent event) {
            // tableModel.disconnectFromDatabase();
            System.exit(0);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfId = new javax.swing.JTextField();
        jbtUpdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfIc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jtfContact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfSalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaAddress = new javax.swing.JTextArea();
        jlIcon = new javax.swing.JLabel();
        jlPassword = new javax.swing.JLabel();
        jbtAdd = new javax.swing.JButton();
        jbtRemove = new javax.swing.JButton();
        jlAdd = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jbtSearch = new javax.swing.JButton();
        jcbManager = new javax.swing.JCheckBox();
        jcbStaff = new javax.swing.JCheckBox();
        jlClick = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtCreate = new javax.swing.JButton();
        jbtUpdate1 = new javax.swing.JButton();
        jbtDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jtfId.setEnabled(false);

        jbtUpdate.setText("Update");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));

        jLabel10.setText("Staff ID:");

        jtfID.setEnabled(false);
        jtfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Staff Name:");

        jtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNameActionPerformed(evt);
            }
        });
        jtfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNameKeyTyped(evt);
            }
        });

        jLabel4.setText("Staff IC:");

        jtfIc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIcActionPerformed(evt);
            }
        });
        jtfIc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIcKeyTyped(evt);
            }
        });

        jLabel8.setText("Password");

        jpfPassword.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jpfPasswordInputMethodTextChanged(evt);
            }
        });
        jpfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfPasswordActionPerformed(evt);
            }
        });
        jpfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpfPasswordKeyTyped(evt);
            }
        });

        jLabel7.setText("Contact No:");

        jtfContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfContactActionPerformed(evt);
            }
        });
        jtfContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfContactKeyTyped(evt);
            }
        });

        jLabel3.setText("Salary:");

        jtfSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSalaryActionPerformed(evt);
            }
        });
        jtfSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSalaryKeyTyped(evt);
            }
        });

        jLabel5.setText("Address");

        jtaAddress.setColumns(20);
        jtaAddress.setRows(5);
        jScrollPane1.setViewportView(jtaAddress);

        jlIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jlPassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jlPassword.setForeground(java.awt.Color.red);
        jlPassword.setText("*Minimum5 Maximum14 *");

        jbtAdd.setText("Add");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });

        jbtRemove.setText("Remove");
        jbtRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveActionPerformed(evt);
            }
        });

        jlAdd.setForeground(java.awt.Color.red);
        jlAdd.setText("Upload Your Picture");

        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        jtfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSearchKeyTyped(evt);
            }
        });

        jbtSearch.setBackground(new java.awt.Color(51, 51, 255));
        jbtSearch.setForeground(new java.awt.Color(51, 51, 255));
        jbtSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        jbtSearch.setBorderPainted(false);
        jbtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchActionPerformed(evt);
            }
        });

        jcbManager.setText("Manager");
        jcbManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbManagerActionPerformed(evt);
            }
        });

        jcbStaff.setText("Staff");
        jcbStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStaffActionPerformed(evt);
            }
        });

        jlClick.setForeground(java.awt.Color.red);
        jlClick.setText("*Select Position*");

        jLabel6.setText("Position");

        jbtCreate.setText("Create");
        jbtCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCreateActionPerformed(evt);
            }
        });

        jbtUpdate1.setText("Update");
        jbtUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdate1ActionPerformed(evt);
            }
        });

        jbtDelete.setText("Delete");
        jbtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (1).jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(java.awt.Color.red);
        jLabel9.setText("Overview of all the employees");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtRemove, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfIc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbStaff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbManager))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlClick)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(332, 332, 332))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfIc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jtfContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jlAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtAdd)
                            .addComponent(jbtRemove))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlClick)
                    .addComponent(jcbStaff)
                    .addComponent(jcbManager))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtDelete)
                    .addComponent(jbtUpdate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jbtCreate))
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:

        String id = jtfSearch.getText();
        domain.Staff stf = stfControl.selectRecord(id);

        if (stf != null) {

            jtfIc.setText(stf.getIc());
            jtfID.setText(id);
            jtfName.setText(stf.getName());
            jpfPassword.setText(stf.getPassword());
            jtfContact.setText(stf.getContactNo());
            jtaAddress.setText(stf.getAddress());
            jtfSearch.setText("");
            jtfSalary.setText("" + stf.getSalary());
            jlIcon.setIcon(stf.getIcon().getImage());
            Position(id);

        } else {
            JOptionPane.showMessageDialog(null, "Invalid user ID ", "STAFF NOT FOUND", JOptionPane.ERROR_MESSAGE);
            Clear();

        }
    }//GEN-LAST:event_jtfSearchActionPerformed

    private void jtfSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSearchKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetterOrDigit(c) && jtfSearch.getText().length() < 5) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfSearchKeyTyped

    private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed

        String id = jtfSearch.getText();
        domain.Staff stf = stfControl.selectRecord(id);

        if (stf != null) {
            jtfIc.setText(stf.getIc());
            jtfID.setText(id);
            jtfName.setText(stf.getName());
            jpfPassword.setText(stf.getPassword());
            jtfContact.setText(stf.getContactNo());
            jtaAddress.setText(stf.getAddress());
            jtfSalary.setText("" + stf.getSalary());
            Position(id);
            jlIcon.setIcon(stf.getIcon().getImage());
            jtfSearch.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Invalid user ID ", "STAFF NOT FOUND", JOptionPane.ERROR_MESSAGE);
            Clear();

        }
    }//GEN-LAST:event_jbtSearchActionPerformed

    private void jtfNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c) && jtfName.getText().length() < 30) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfNameKeyTyped

    private void jtfIcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIcKeyTyped
        // TODO add your handling code here:char c = evt.getKeyChar();
        char c = evt.getKeyChar();

        if (Character.isDigit(c) && jtfIc.getText().length() < 14) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }
    }//GEN-LAST:event_jtfIcKeyTyped

    private void jpfPasswordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jpfPasswordInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfPasswordInputMethodTextChanged

    private void jpfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfPasswordActionPerformed

    private void jpfPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfPasswordKeyTyped
        // TODO add your handling code here:
        if (jpfPassword.getText().length() < 4) {
            jlPassword.setVisible(true);
        }
        if (jpfPassword.getText().length() >= 4 || jpfPassword.getText().length() == 0) {
            jlPassword.setVisible(false);
        }

    }//GEN-LAST:event_jpfPasswordKeyTyped

    private void jtfContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContactActionPerformed

    private void jtfContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if (Character.isDigit(c) && jtfContact.getText().length() < 11) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }

    }//GEN-LAST:event_jtfContactKeyTyped

    private void jtfSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSalaryActionPerformed

    private void jtfSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSalaryKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isDigit(c) && jtfSalary.getText().length() < 8) {
            // OK

        } else {
            // Ignore this character
            evt.consume();
        }

    }//GEN-LAST:event_jtfSalaryKeyTyped

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed


    }//GEN-LAST:event_jbtUpdateActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        int result = jfcPhoto.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jfcPhoto.getSelectedFile();
            String fileName = file.getAbsolutePath();
            imgPhoto = new ImageIcon(fileName);

            // Image image = imgPhoto.getImage().getScaledInstance(120, 80, Image.SCALE_SMOOTH);
            // imgPhoto.setImage(image);
            jlIcon.setIcon(imgPhoto);

            repaint();
            jlAdd.setVisible(false);
        }
    }//GEN-LAST:event_jbtAddActionPerformed

    private void jbtRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveActionPerformed
        // TODO add your handling code here:
        jlIcon.setIcon(null);
    }//GEN-LAST:event_jbtRemoveActionPerformed

    private void jcbManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbManagerActionPerformed
        // TODO add your handling code here:
        jcbStaff.setSelected(false);
        jlClick.setVisible(false);
    }//GEN-LAST:event_jcbManagerActionPerformed

    private void jcbStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStaffActionPerformed
        // TODO add your handling code here:
        jcbManager.setSelected(false);
        jlClick.setVisible(false);
    }//GEN-LAST:event_jcbStaffActionPerformed

    private void jbtUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdate1ActionPerformed

        String id = jtfID.getText();

        domain.Staff staff = stfControl.selectRecord(id);
        
         if (jcbManager.isSelected() == false && jcbStaff.isSelected() == false) {
            jlClick.setVisible(true);
        }
        if (jlIcon.getIcon() == null) {
            jlAdd.setVisible(true);
        }
        
         if (jtfName.getText().equals("") || jtfIc.getText().equals("") || jtfContact.getText().equals("") || jtaAddress.getText().equals("")
                || jtfSalary.getText().equals("")
                || jpfPassword.getText().equals("") || jpfPassword.getText().length() < 4 || jlIcon.getIcon() == null) {
            JOptionPane.showMessageDialog(null, "Please fill in all the information", "Incomplete", JOptionPane.INFORMATION_MESSAGE);
        }

       
        
        
         else{
             if(staff != null) {
            String position = "";
            domain.Staff stf = (new StaffDA().getRecord(jtfSearch.getText()));
            double salary = Double.parseDouble(jtfSalary.getText());
            Icon icon = new Icon();
            if (jcbManager.isSelected()) {
                position = "Manager";
            } else if (jcbStaff.isSelected()) {
                position = "Staff";
            }

            try {
                String selectedFile = jfcPhoto.getSelectedFile().getAbsolutePath();

                ImageIcon imageIcon = new ImageIcon(selectedFile);

                URL url = new URL("file:///" + selectedFile);

                icon = new Icon(imageIcon, url);

            } catch (NullPointerException ex) {
                ImageIcon imageIcon = staff.getIcon().getImage();
                icon = new Icon(imageIcon);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "exception occurs" + ex.getMessage());
            }

            int option = JOptionPane.showConfirmDialog(null, "Confirm update " + jtfName.getText() + "'s information?", "Update Employee", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                stf = new domain.Staff(id, jtfIc.getText(), jtfName.getText(), jpfPassword.getText(), jtfContact.getText(), jtaAddress.getText(), position, salary, icon);
                try {
                    stfControl.updateRecord(stf);
                } catch (SQLException | IOException ex) {
                    Logger.getLogger(MaintainStaff.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, jtfName.getText() + "'s information updated successfully");
                Clear();
            } else {

            }
             }
         else {
            JOptionPane.showMessageDialog(null, "Employee record not found .", "RECORD NOT FOUND", JOptionPane.ERROR_MESSAGE);
        }
         }
    }//GEN-LAST:event_jbtUpdate1ActionPerformed

    private void jbtCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCreateActionPerformed
        String id = "";
        String position = "";
        boolean decision = false;
        domain.Staff staff = stfControl.selectRecord(id);
        if(!jtfID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter the clear button", "Clean", JOptionPane.INFORMATION_MESSAGE);
        
        if (jtfName.getText().equals("") || jtfIc.getText().equals("") || jtfContact.getText().equals("") || jtaAddress.getText().equals("")
                || jtfSalary.getText().equals("")
                || jpfPassword.getText().equals("") || jpfPassword.getText().length() < 4 || jlIcon.getIcon() == null) {
            JOptionPane.showMessageDialog(null, "Please fill in all the information", "Incomplete", JOptionPane.INFORMATION_MESSAGE);
        }

        if (jcbManager.isSelected() == false && jcbStaff.isSelected() == false) {
            jlClick.setVisible(true);
        }
        if (jlIcon.getIcon() == null) {
            jlAdd.setVisible(true);

        }
        }else {
            do {
                id = GenarateId();
                position = GeneratePosition(id);
                staff = stfControl.selectRecord(id);
                if (staff == null) {
                    double salary = Double.parseDouble(jtfSalary.getText());
                    decision = true;

                    try {

                        String selectedFile = jfcPhoto.getSelectedFile().getAbsolutePath();
                        ImageIcon imageIcon = new ImageIcon(selectedFile);

                        URL url1 = new URL("file:///" + selectedFile);
                        Icon icon = new Icon(imageIcon, url1);

                        staff = new domain.Staff(id, jtfName.getText(), jpfPassword.getText(), jtfContact.getText(), jtaAddress.getText(), jtfIc.getText(), position, salary, icon);

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "exception occurs" + ex.getMessage());
                    }

                }
                int option = JOptionPane.showConfirmDialog(null, "Confirm adding as employee ?", "New Employee", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    stfControl.addRecord(staff);
                    JOptionPane.showMessageDialog(null, "Your ID is " + id);

                    Clear();
                }

            } while (decision != true);
        }
    }//GEN-LAST:event_jbtCreateActionPerformed

    private void jbtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteActionPerformed
        String id = jtfID.getText();
        domain.Staff stf = stfControl.selectRecord(id);

        if (stf != null) {
            jbtRemove.setEnabled(false);
            jtfIc.setEnabled(false);
            jbtAdd.setEnabled(false);
            jtfContact.setEnabled(false);
            jpfPassword.setEnabled(false);
            jtaAddress.setOpaque(false);
            jtaAddress.setEnabled(false);
            jcbStaff.setEnabled(false);
            jcbManager.setEnabled(false);
            jtfSalary.setEnabled(false);
            jtfName.setEnabled(false);
            jtfIc.setText(stf.getIc());
            jtfName.setText(stf.getName());
            jpfPassword.setText(stf.getPassword());
            jtfContact.setText(stf.getContactNo());
            jtaAddress.setText(stf.getAddress());
            Position(id);
            jlIcon.setIcon(stf.getIcon().getImage());

            int option = JOptionPane.showConfirmDialog(null, "Do you wish to remove " + jtfName.getText() + "?", "Delete Employee", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                stfControl.deleteRecord(stf);
                JOptionPane.showMessageDialog(null, jtfName.getText() + " successfully delete");

                Clear();

            } else {
                jtfIc.setEnabled(true);
                jbtAdd.setEnabled(true);
                jbtRemove.setEnabled(true);
                jtfContact.setEnabled(true);
                jpfPassword.setEnabled(true);
                jtaAddress.setOpaque(true);
                jtaAddress.setEnabled(true);
                jcbStaff.setEnabled(true);
                jcbManager.setEnabled(true);
                jtfSalary.setEnabled(true);
                jtfName.setEnabled(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Invalid user ID ", "STAFF NOT FOUND", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jbtDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        dispose();
         Staff staff = new Staff(stf);
        new StaffTable(staff).setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        Staff staff = new Staff(stf);
        new Main(staff).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIDActionPerformed

    private void jtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNameActionPerformed

    private void jtfIcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaintainStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaintainStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaintainStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaintainStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                       MaintainStaff frm =new MaintainStaff() ;
                } catch (Exception e) {
                    
                }
            }
        });
    }

    public void Position(String id) {
        domain.Staff staff = stfControl.selectRecord(id);

        if (staff.getPositon().equals("Manager")) {
            jcbStaff.setSelected(false);
            jcbManager.setSelected(true);

        } else {
            jcbStaff.setSelected(true);
            jcbManager.setSelected(false);

        }

    }

    public String GeneratePosition(String id) {
        String position = "";
        if (id.charAt(0) == 'M') {
            position = "Manager";
        } else {
            position = "Staff";
        }
        return position;
    }

    public String GenarateId() {
        String id = "";
        int a = (int) (Math.random() * 9999);
        if (a < 10 && jcbManager.isSelected()) {

            id = "M00" + a;
        } else if (a < 10000 && jcbManager.isSelected()) {

            id = "M" + a;
        } else if (a < 100 && jcbManager.isSelected()) {

            id = "M0" + a;
        } else if (a < 1000 && jcbManager.isSelected()) {

            id = "M" + a;
        } else if (a < 10 && jcbStaff.isSelected()) {

            id = "S00" + a;
        } else if (a < 100 && jcbStaff.isSelected()) {

            id = "S0" + a;
        } else if (a < 1000 && jcbStaff.isSelected()) {

            id = "S" + a;
        } else if (a < 10000 && jcbStaff.isSelected()) {

            id = "S" + a;
        }
        return id;
    }

    public void Clear() {
        jtfID.setText("");
        jtfName.setText("");
        jtfIc.setText("");
        jpfPassword.setText("");
        jtaAddress.setText("");
        jtfContact.setText("");
        jtfSalary.setText("");
        jcbStaff.setSelected(false);
        jcbManager.setSelected(false);
        jtfSearch.setText("");
        jlIcon.setIcon(null);
        jtfIc.setEnabled(true);
        jbtAdd.setEnabled(true);
        jbtRemove.setEnabled(true);
        jtfContact.setEnabled(true);
        jpfPassword.setEnabled(true);
        jtaAddress.setOpaque(true);
        jtaAddress.setEnabled(true);
        jcbStaff.setEnabled(true);
        jcbManager.setEnabled(true);
        jtfSalary.setEnabled(true);
        jtfName.setEnabled(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtCreate;
    private javax.swing.JButton jbtDelete;
    private javax.swing.JButton jbtRemove;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JButton jbtUpdate1;
    private javax.swing.JCheckBox jcbManager;
    private javax.swing.JCheckBox jcbStaff;
    private javax.swing.JLabel jlAdd;
    private javax.swing.JLabel jlClick;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextArea jtaAddress;
    private javax.swing.JTextField jtfContact;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfIc;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfSalary;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables
}
