/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;/*author: huiwen*/


import control.TransactionControl;
import domain.Cart;
import domain.OrderList;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;

public class MaintaiItemFrame extends javax.swing.JFrame {

    private String stf;
    private TransactionControl transControl;
    private Cart cart;
    private String transID;
    private JList jlstCart;
    private int orderCount;
    private int tempCount;
    private JFrame itemEdit = new JFrame();
    private PaymentFormPanel payment;

    public MaintaiItemFrame(String staff) {
        stf = staff;
        transControl = new TransactionControl();
        transID = transControl.getAfterLastCode();
        cart = new Cart(transID);
        jlstCart = new JList(cart.getCartData());

        initComponents();
        setLocationRelativeTo(null);
        int delay = 500;
        tempCount = OrderList.getNumOfOrder();
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                orderCount = OrderList.getNumOfOrder();
                if (cart.getCounter() >= 0 && orderCount != tempCount) {
                    jlstCart = new JList(cart.getCartData());
                    jpEast.setViewportView(jlstCart);
                    tempCount++;
                }
            }
        };
        new Timer(delay, taskPerformer).start();
        pack();
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
        setTitle("Mcd Ordering System");
    }

    public MaintaiItemFrame() {
        transControl = new TransactionControl();
        transID = transControl.getAfterLastCode();
        cart = new Cart(transID);
        jlstCart = new JList(cart.getCartData());

        initComponents();
        setLocationRelativeTo(null);
        int delay = 500;
        tempCount = OrderList.getNumOfOrder();
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                orderCount = OrderList.getNumOfOrder();
                if (cart.getCounter() >= 0 && orderCount != tempCount) {
                    jlstCart = new JList(cart.getCartData());
                    jpEast.setViewportView(jlstCart);
                    tempCount++;
                }
            }
        };
        new Timer(delay, taskPerformer).start();
        pack();
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        setTitle("Mcd Ordering System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCenter = new javax.swing.JScrollPane(new displayItemPanel(cart));
        jpEast = new javax.swing.JScrollPane(jlstCart);
        jLabel2 = new javax.swing.JLabel();
        jbtCheckOut = new javax.swing.JButton();
        jbtEditCart = new javax.swing.JButton();
        jbtManage = new javax.swing.JButton();
        jbtRefresh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpCenter.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cart");

        jbtCheckOut.setText("Check Out");
        jbtCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCheckOutActionPerformed(evt);
            }
        });

        jbtEditCart.setText("Edit Cart");
        jbtEditCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditCartActionPerformed(evt);
            }
        });

        jbtManage.setText("Manage Item");
        jbtManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManageActionPerformed(evt);
            }
        });

        jbtRefresh.setText("Refresh List");
        jbtRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRefreshActionPerformed(evt);
            }
        });

        jButton1.setText("Back to Main");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpEast)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtRefresh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtManage))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtEditCart)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtCheckOut)))))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtRefresh)
                            .addComponent(jbtManage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpEast, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtCheckOut)
                            .addComponent(jbtEditCart)
                            .addComponent(jButton1))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jpCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManageActionPerformed
        new MaintainAddItemFrame();
    }//GEN-LAST:event_jbtManageActionPerformed

    private void jbtRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRefreshActionPerformed

        jpCenter.setViewportView(new displayItemPanel(cart));

    }//GEN-LAST:event_jbtRefreshActionPerformed

    private void jbtEditCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditCartActionPerformed
        int[] listInt = jlstCart.getSelectedIndices();
        if (listInt.length > 1) {
            JOptionPane.showMessageDialog(null, "System can only edit 1 item at a time!");
        }
        OrderList ord = cart.getOrderItem(listInt[0]);
        if (ord != null) {
            itemEdit.removeAll();
            itemEdit.revalidate();
            itemEdit.repaint();
            itemEdit = new ItemDescFrame(ord.getItem(), cart);
        } else {
            JOptionPane.showMessageDialog(null, "Nothing is selected!");

        }

    }//GEN-LAST:event_jbtEditCartActionPerformed

    private void jbtCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCheckOutActionPerformed

        if (cart.getFinalCart().size() != 0) {
            payment = new PaymentFormPanel(cart.getFinalCart(), stf);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Please insert Item to cart.", "Cart is Empty", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtCheckOutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaintaiItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaintaiItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaintaiItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaintaiItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MaintaiItemFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtCheckOut;
    private javax.swing.JButton jbtEditCart;
    private javax.swing.JButton jbtManage;
    private javax.swing.JButton jbtRefresh;
    private javax.swing.JScrollPane jpCenter;
    private javax.swing.JScrollPane jpEast;
    // End of variables declaration//GEN-END:variables
}
